### ISSUE TITLE
localizedDescription for ShellOutError

### ISSUE THREAD

**Issue by muukii** [JohnSundell/ShellOut#14]
Hi, Thanks for the helpful library.

I think ShellOutError needs to improve printing.
Currently, ShellOutError prints following.

```
let error: ShellOutError
print(error)
```

```
ShellOutError(terminationStatus: 1, errorData: 32 bytes, outputData: 0 bytes)
```

I want a more helpful description. 
I think to convert to string from errorData.

What do you think?

**Comment by JohnSundell** [comment]
Sounds like a plan 👍 Want to submit a PR?

**Comment by muukii** [comment]
@JohnSundell 
Thanks.
I've submitted PR.
Please check it.

#16

**Comment by JohnSundell** [comment]
Implemented here https://github.com/JohnSundell/ShellOut/pull/20. New release including this patch coming soon 👍
