### ISSUE TITLE
Can't load framework in Command Line Tool

### ISSUE THREAD

**Issue by onesentinel** [JohnSundell/ShellOut#26]
`dyld: Library not loaded: @rpath/ShellOut.framework/Versions/A/ShellOut
  Referenced from: /Users/MYUSER/Library/Developer/Xcode/DerivedData/MyAppName-ekiclknclczpksfxqtybkeebjynw/Build/Products/Debug/SecurityHelper
  Reason: image not found
(lldb) `

Binary with Library is Linked

**Comment by JohnSundell** [comment]
You can't link to frameworks in a Command Line Tool. Either simply drag the file `ShellOut.swift` into your Xcode project or use the Swift Package Manager to include it as a dependency 🙂. Please see the README for installation instructions 👍
