### ISSUE TITLE
Add Compatibility with Commands like "vi"

### ISSUE THREAD

**Issue by ghost** [JohnSundell/ShellOut#52]
Please add a feature where you can run interactive commands and not get stuck on a black screen...

A lot of commands require you to put information as the command runs. Some examples are:
- `vi`
- `npm init`
- `sudo`
- My Project

So please add an option to use interactive commands as well as normal ones.
```Swift
try shellOut(to: "vi README.md", interactive: true)
```

This is similar to #35, but with a little more context.

**Comment by ghost** [comment]
I found [my own way](https://github.com/SwiftStars/SwiftShell) to do this. It requires some C++, but works for me.

**Comment by ismetanin** [comment]
@BenSova Hi! Can't open a link that you provided for your solution :(

**Comment by ghost** [comment]
@ismetanin I merged it into a different project, [here](https://github.com/SwiftStars/StdLibX).

**Comment by ismetanin** [comment]
@BenSova thank you!
