### ISSUE TITLE
Cut a new tag?

### ISSUE THREAD

**Issue by toshi0383** [JohnSundell/ShellOut#8]
Hi. I use ShellOut for my app and this is so useful!😄
I've been using my own fork of ShellOut in order to use the latest master via SwiftPM.
Are you going to push a new tag?

**Comment by JohnSundell** [comment]
Hi @toshi0383 👋 Sorry about the delay, version `1.2.0` of ShellOut has now been released. It comes with a pretty exciting new feature to pre-define commands, hope you like it 😄
