### ISSUE TITLE
Add sample Xcode project?

### ISSUE THREAD

**Issue by getaaron** [JohnSundell/ShellOut#9]
Running

```bash
pod try https://github.com/JohnSundell/ShellOut
```

should clone the repo and open a sample project, but produces this error:

> Unable to find any project in the source files of the Pod

This is because it [can't find a sample project](https://github.com/CocoaPods/cocoapods-try/blob/2c0840a6ba64056931622abc1d11479ffcc4a31b/lib/pod/command/try.rb#L158-L159).

It would be nice to create a simple command line project which just includes `ShellOut` and some examples, and/or maybe a playground file.

**Comment by JohnSundell** [comment]
Hi @getaaron 👋 

I honestly don't think ShellOut needs an example project, it's such a simple tool and pretty much the entire API is described in the README file. If you have any questions or need any help getting started with ShellOut I'd be more than happy to help, but I don't think it's worth maintaining an Xcode project for this one.

Thanks anyway for your suggestion 👍
